require 'buildr'
require 'buildr/java'
require 'buildr/android/version'
require 'buildr/android/config'
require 'buildr/android/layout'
require 'buildr/android/project_extension'
require 'buildr/android/manifest'
require 'buildr/android/test'

require 'buildr/eclipse/android'